# Generated by Django 2.1.7 on 2019-03-19 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goodreads_user_id", models.IntegerField()),
                ("name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("visibility", models.BooleanField()),
                ("access_token", models.CharField(max_length=255)),
                ("access_secret", models.CharField(max_length=255)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        )
    ]
