# Generated by Django 2.1.7 on 2019-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book_report", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="visibility",
            field=models.BooleanField(db_index=True),
        ),
        migrations.RunSQL(
            "CREATE INDEX idx_gid_visibility ON book_report_user (goodreads_user_id, visibility)"
        ),
    ]
