"""add users table

Revision ID: 318ea2254810
Revises: 
Create Date: 2017-11-20 22:46:29.834587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318ea2254810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('goodreads_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('access_secret', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('goodreads_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
